version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Phase-3-Docker/Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - ./Phase-1-Development/Fashion-fusion:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fashionfusion
    ports:
      - "3307:3306"
